'use client';

// -------------------- ROOT ----------------------------------------
export * from './shared-ui';

// -------------------- ASSETS ----------------------------------------
export * from '../../../assets/images';

// -------------------- HOOKS ----------------------------------------
export * from './hooks/useDeviceDetect';

// -------------------- CONTEXTS ----------------------------------------
export * from './contexts/shared-app.context';
export * from './contexts/uc-header.context';

// -------------------- FORM-CONTROLS ----------------------------------------
export * from './form-controls/uc-button/uc-button';
export * from './form-controls/uc-switch/uc-switch';

// -------------------- COMPONENTS ----------------------------------------
export * from './components/header-profile-popover/header-profile-popover';
export * from './components/what-is-uc-credit-modal/what-is-uc-credit-modal';
export * from './components/profile-verify-otp/profile-verify-otp';
export * from './components/select-header-banner--modal/select-header-banner--modal';
export * from './components/delete-account-modal/delete-account-modal';
export * from './components/share-via-social-media-popup/share-via-social-media-popup';
export * from './components/coin-screen/coin-screen';
export * from './components/credit-screen/credit-screen';
export * from './components/earnings/earnings';
export * from './components/otp-input-tabs/otp-input-tabs';
export * from './components/buddy-invite/buddy-invite';
export * from './components/uc-notifications-settings/uc-notifications-settings';
export * from './components/delete-traveler-modal/delete-traveler-modal';
export * from './components/uc-profile-saved-traveler-card/uc-profile-saved-traveler-card';
export * from './components/uc-profile-manage-travelers/uc-profile-manage-travelers';
export * from './components/edit-travel-profile/edit-travel-profile';
export * from './components/edit-defence-profile/edit-defence-profile';
export * from './components/edit-personal-profile/edit-personal-profile';
export * from './components/edit-profile/edit-profile';
export * from './components/uc-date-picker/uc-date-picker';
export * from './components/gender-selection-panel/gender-selection-panel';
export * from './components/my-profile/my-profile';
export * from './components/uc-body-portal/uc-body-portal';
export * from './components/uc-footer/uc-footer';
export * from './components/uc-header/uc-header';
export * from './components/uc-carousel/uc-carousel';
export * from './components/multi-select-filter/multi-select-filter';
export * from './components/slider-filter/slider-filter';
export * from './components/route-navigation/route-navigation';
export * from './components/uc-date-price-carousel/uc-date-price-carousel';
export * from './components/uc-visa-services-carousel/uc-visa-services-carousel';
export * from './components/uc-bank-offer-carousel/uc-bank-offer-carousel';
export * from './components/uc-fauji-fares-carousel/uc-fauji-fares-carousel';
export * from './components/uc-discount-coupon/uc-discount-coupon';
export * from './components/discount-coupon-card/discount-coupon-card';
export * from './components/uc-fare-breakup/uc-fare-breakup';
export * from './components/uc-checkbox-row/uc-checkbox-row';
export * from './components/uc-saved-traveller-card/uc-saved-traveller-card';
export * from './components/contact-details-form/contact-details-form';
export * from './components/pay-advertisement/pay-advertisement';
export * from './components/proceed-to-pay/proceed-to-pay';
export * from './components/traveller-contact-details-card/traveller-contact-details-card';
export * from './components/add-traveler-card/add-traveler-card';
export * from './components/added-traveler-card/added-traveler-card';
export * from './components/uc-popup/uc-popup';
export * from './components/uc-stepper-container/uc-stepper-container';
export * from './components/uc-sort-menu/uc-sort-menu';
export * from '../../../assets/animations/uc_flight_loading_animtion';
export * from './components/uc-payments/uc-payments';
export * from './components/uc-traveller-form/uc-traveller-form';
export * from './components/uc-card/uc-card';
// export * from './components/uc-confirmation/uc-confirmation';
export * from './components/web-check-in/web-check-in';
export * from '../../flights/booking-details/components/change-in-plans/change-in-plans';
export * from '../../flights/booking-details/components/change-in-plans-option/change-in-plans-option';
export * from './components/faqs/faqs';
export * from './components/banner-with-icon/banner-with-icon';
export * from '../../flights/booking-details/components/booked-contact-details/booked-contact-details';
export * from './components/add-insurance/add-insurance';
export * from '../../flights/booking-details/components/baggage-details/baggage-details';
export * from '../../flights/booking-details/components/booked-traveller-details/booked-traveller-details';
export * from './components/m-site-uc-header/m-site-uc-header';
export * from './components/confirm-and-pay-popup/confirm-and-pay-popup';
export * from './components/congrats-banner-with-icon/congrats-banner-with-icon';
export * from './components/saved-money/saved-money';
export * from './components/total-pay-msite-accordian/total-pay-msite-accordian';
export * from './components/uc-ctabanner/uc-ctabanner';
export * from './components/uc-promo/uc-promo';
export * from './components/uc-support/uc-support';
export * from './components/uc-follow-us-and-download/uc-follow-us-and-download';
export * from './components/traveller-details-without-accordian/traveller-details-without-accordian';
export * from './components/cancel-trip-fare-details/cancel-trip-fare-details';
export * from './components/thankyou-popup/thankyou-popup';
export * from './components/thankyou-popup-content/thankyou-popup-content';
export * from './components/confirmation-summary/confirmation-summary';
export * from './components/uc-rating/uc-rating';
