export const bookingData = {
  collectionStatus: 1,
  isExclusive: false,
  isLtcSearch: false,
  status: 'booked',
  brandName: 'SpiceSaver',
  contactDetails: {
    name: {
      firstName: 'vishal',
      lastName: 'user',
      middleName: 'taral',
    },
    email: 'vishal.taral@partners.udchalo.com',
    phoneNumber: '7767034533',
  },
  flightId: '4dba81a7-4f06-42da-89da-c9d9b2fc0b81',
  isIvyClubBooking: false,
  dateOfJourney: '2023-10-04T23:55:00',
  pnr: 'A51SPI',
  fare: {
    cmfDiscount: 0,
    totalFare: 7671,
    airlineRescheduleFee: 0,
    totalBaggageFare: 0,
    priceDiff: 0,
    fareCategory: 'Normal',
    totalSeatFare: 0,
    baseTotalFare: 6477,
    totalTax: 330,
    ancillariesRefundedAmount: 0,
    totalFee: 565,
    totalMealFare: 0,
    totalAncillariesFare: 0,
    totalConvenienceFee: 299,
    passengerFares: [
      {
        totalTax: 330,
        classOfService: 'V',
        fees: [
          {
            amount: 50,
            code: 'RCS',
          },
          {
            amount: 50,
            code: 'TRF',
          },
          {
            amount: 465,
            code: 'UDF',
          },
          {
            amount: 0,
            code: 'udChalo Service Charge',
          },
          {
            amount: 299,
            code: 'Merchant Fee',
          },
        ],
        baseFare: 6477,
        totalFare: 7671,
        quantity: 1,
        passengerType: 'adult',
        totalFee: 565,
        fareBasisCode: 'VSAV',
        taxes: [
          {
            amount: 3,
            code: 'CST',
          },
          {
            amount: 162,
            code: 'CST',
          },
          {
            amount: 3,
            code: 'SST',
          },
          {
            amount: 162,
            code: 'SST',
          },
        ],
        totalConvenienceFee: 299,
      },
    ],
    fareType: 0,
    brand: {
      name: 'SpiceSaver',
      qualifier: 'RS',
    },
    oldBookingFare: 0,
  },
  segments: [
    {
      classOfService: 'V',
      arriveTerminal: '3',
      aircraft: null,
      handBaggage: 7,
      origin: 'PNQ',
      checkInBaggage: 15,
      arriveDate: '2023-10-05T02:00:00',
      destination: 'DEL',
      destinationCountryCode: 'IN',
      cabin: 'Economy',
      departTerminal: '1',
      flightNumber: '8184',
      layoverMinutes: 610,
      duration: 125,
      seatAvailable: 0,
      layoverAirportCode: 'DEL',
      isInternational: false,
      originCountryCode: 'IN',
      departDate: '2023-10-04T23:55:00',
      stops: 0,
      airline: 'SG',
      airlineName: 'SpiceJet',
      handBaggageText: null,
      mileage: 0,
    },
    {
      classOfService: 'V',
      arriveTerminal: '1',
      aircraft: null,
      handBaggage: 7,
      origin: 'DEL',
      checkInBaggage: 15,
      arriveDate: '2023-10-05T14:35:00',
      destination: 'BOM',
      destinationCountryCode: 'IN',
      cabin: 'Economy',
      departTerminal: '1D',
      flightNumber: '157',
      layoverMinutes: 0,
      duration: 145,
      seatAvailable: 0,
      layoverAirportCode: null,
      isInternational: false,
      originCountryCode: 'IN',
      departDate: '2023-10-05T12:10:00',
      stops: 0,
      airline: 'SG',
      airlineName: 'SpiceJet',
      handBaggageText: null,
      mileage: 0,
    },
  ],
  loginDetails: {
    isLoggedIn: true,
    loginPage: 'Already LoggedIn',
  },
  freeReschedulingAllowed: false,
  userId: 'a09072ac-aad2-4d45-acb2-3d7658b55a66',
  arriveDate: '2023-10-05T14:35:00',
  isCabServiceOpted: 0,
  ancillariesCancelPenalties: {
    baggage: {
      baggageRefundHours: 0,
      isBaggageRefundable: true,
    },
    seats: {
      seatRefundHours: 0,
      isSeatRefundable: true,
    },
    meals: {
      mealRefundHours: 0,
      isMealRefundable: true,
    },
  },
  donationAmount: 0,
  destination: 'BOM',
  isBalmerLawrie: false,
  isPostAncillaryPayment: false,
  destinationCityName: 'Mumbai',
  isEnabled: 1,
  duration: 880,
  createdMMYYYY: '10-2023',
  ltcDetails: {},
  origin: 'PNQ',
  phoneNumber: '7767034533',
  isOfflineDiscount: false,
  isOfflineRescheduled: false,
  reschedulingPolicy: [
    {
      amount: 3350,
      hours: 6,
      additionalGstPercent: 0,
      penaltyType: 0,
    },
    {
      amount: 2850,
      hours: 96,
      additionalGstPercent: 0,
      penaltyType: 0,
    },
  ],
  createdAt: '2023-10-04T10:55:20.731Z',
  source: 'website',
  isSeries: false,
  isCovidBooking: false,
  isRescheduledBooking: false,
  isDefence: true,
  handBaggage: 7,
  supplierState: {
    name: 'SpicejetAPIV4Defence',
  },
  legId: 'Leg:933d1d12-52d2-4183-8e85-a74a1f0186ef|SCPREFIX:PNQ:BOM:1696377600000',
  passengers: [
    {
      serviceNumber: '111111111111',
      passengerType: 'adult',
      gender: 'male',
      name: {
        firstName: 'Vishal',
        lastName: 'Taral',
        middleName: null,
        title: 'mr',
      },
      passengerId: 'a2be4226-8e69-45c3-ac78-6a9b38804e9d',
      bookingStatus: 'booked',
      dateOfBirth: 'Sat Oct 04 2003',
      travellerId: null,
      passportDetails: null,
      eticketNumber: 'A51SPI',
    },
  ],
  email: 'vishal.taral@partners.udchalo.com',
  discount: {
    description: '',
    amount: 200,
    metadata: {
      is_hidden: false,
      coupon_type: 'per_booking',
    },
    code: 'PPP1',
    type: 'perBooking',
    redemption: '12742',
  },
  isLCC: true,
  destinationCountryCode: 'IN',
  airline: 'SG',
  isSupplierSeries: false,
  freeMeal: false,
  checkInBaggage: 25,
  createdDate: '2023-10-4',
  departDate: '2023-10-04T23:55:00',
  isInsuranceOpted: false,
  isDonationOpted: false,
  originCountryCode: 'IN',
  brand: {
    category: 'B',
  },
  collectLater: false,
  createdFixedDate: '2023-10-04',
  isAllianceAir: false,
  isRefundable: true,
  cancelPenalties: [
    {
      amount: 3600,
      hours: 2,
      additionalGstPercent: 0,
      udchaloCancellationFee: 250,
      penaltyType: 0,
    },
    {
      amount: 3100,
      hours: 96,
      additionalGstPercent: 0,
      udchaloCancellationFee: 250,
      penaltyType: 0,
    },
  ],
  freeCancellationAllowed: false,
  rewardEarned: 0,
  stops: 1,
  bookingId: '29187',
  dateOfBooking: '2023-10-04T10:55:20.724Z',
  isSurakshaOpted: false,
  sessionId: '2fe63332-bc6d-4e1b-bd27-d482a459199a',
  sortKey: '#7767034533#user#vishal.taral@partners.udchalo.com#vishal.taral@partners.udchalo.com#',
  platform: 'desktop',
  isCovidCreditShellReschedule: false,
  updatedAt: '2023-10-04T10:55:58.171Z',
  providerBookingRef: '012820023117',
  freeSeatSelectionAllowed: false,
  benefits: [
    {
      key: 'Cabin Baggage',
      value: 'Up to 7 Kgs (1 Piece per person)',
      type: 'exclusion',
    },
    {
      key: 'CheckIn Baggage',
      value: '15 Kgs (1 Piece per person)',
      type: 'exclusion',
    },
    {
      key: 'Meal',
      value: 'Meals are Chargeable.',
      type: 'exclusion',
    },
    {
      key: 'Seat',
      value: 'Seats are chargeable.',
      type: 'exclusion',
    },
    {
      key: 'Cancellation',
      value:
        'Nil cancellation charges Beyond 96 Hours. Cancellation charges up to ₹3,500, up to 2 hours prior departure - Service Fee applicable . Non refundable within 2 hrs. prior to departure from udChalo.',
      type: 'exclusion',
      udchaloCancellationFee: 250,
    },
    {
      key: 'Change Flight',
      value:
        'Reschedule starting INR 2750 per person, 2 hrs. prior to departure from Airline and 6 hrs. prior to departure from udChalo.',
      type: 'exclusion',
    },
  ],
  originCityName: 'Pune',
  rewardUsed: 0,
  isReschedulingAllowed: false,
  payment: null,
  wallet: {
    amount: 7471,
  },
  iswebCheckInEnabled: false,
  webCheckInLink: null,
  alert: null,
};

export const flightDetails = [
  {
    fare: {
      totalFare: 3487,
      baseTotalFare: 2434,
      passengerFares: [
        {
          fees: [
            {
              amount: 65,
              code: 'TRF',
            },
            {
              amount: 500,
              code: 'YQ',
            },
            {
              amount: 12,
              code: 'UDF',
            },
            {
              amount: 91,
              code: 'PSF',
            },
            {
              amount: 0,
              code: 'udChalo Service Charge',
            },
            {
              amount: 249,
              code: 'Merchant Fee',
            },
          ],
          taxes: [
            {
              amount: 61,
              code: 'CST',
            },
            {
              amount: 14,
              code: 'SST',
            },
            {
              amount: 61,
              code: 'SST',
            },
          ],
          baseFare: 2434,
          quantity: 1,
          passengerType: 'Adult',
          totalFee: 668,
          totalFare: 3487,
          totalTax: 136,
          classOfService: 'U',
          fareBasisCode: 'USAV',
          totalConvenienceFee: 249,
        },
      ],
      totalFee: 668,
      totalTax: 136,
      fareType: 0,
      brand: {
        name: 'SpiceSaver',
        qualifier: 'RS',
      },
      fareCategory: 'Normal',
      cmfDiscount: 0,
      totalCorporateConvenienceFees: 249,
      totalConvenienceFee: 249,
      priceDiff: 0,
    },
    isFareChanged: false,
    status: 0,
    error: null,
    leg: {
      legId: 'Leg:e8f81da2-ce76-4b49-aaf4-0761bb23b1f0|SCPREFIX:DEL:IXL:1696809600000',
      departDate: '2023-10-09T08:20:00',
      arriveDate: '2023-10-09T09:20:00',
      departOffset: 0,
      arriveOffset: 0,
      airline: 'SG',
      classOfService: 'U',
      duration: 60,
      fare: {
        totalFare: 3487,
        baseTotalFare: 2434,
        passengerFares: [
          {
            fees: [
              {
                amount: 65,
                code: 'TRF',
              },
              {
                amount: 500,
                code: 'YQ',
              },
              {
                amount: 12,
                code: 'UDF',
              },
              {
                amount: 91,
                code: 'PSF',
              },
              {
                amount: 0,
                code: 'udChalo Service Charge',
              },
              {
                amount: 249,
                code: 'Merchant Fee',
              },
            ],
            taxes: [
              {
                amount: 61,
                code: 'CST',
              },
              {
                amount: 14,
                code: 'SST',
              },
              {
                amount: 61,
                code: 'SST',
              },
            ],
            baseFare: 2434,
            quantity: 1,
            passengerType: 'Adult',
            totalFee: 668,
            totalFare: 3487,
            totalTax: 136,
            classOfService: 'U',
            fareBasisCode: 'USAV',
            totalConvenienceFee: 249,
          },
        ],
        totalFee: 668,
        totalTax: 136,
        fareType: 0,
        brand: {
          name: 'SpiceSaver',
          qualifier: 'RS',
        },
        fareCategory: 'Normal',
        cmfDiscount: 0,
        totalCorporateConvenienceFees: 249,
        totalConvenienceFee: 249,
        priceDiff: 0,
      },
      isLCC: true,
      isDefence: false,
      freeMeal: false,
      isDiscounted: false,
      freeReschedulingAllowed: false,
      freeCancellationAllowed: false,
      freeSeatSelectionAllowed: false,
      isSeries: false,
      origin: 'DEL',
      destination: 'IXL',
      stops: 0,
      isRefundable: true,
      segments: [
        {
          isInternational: false,
          duration: 60,
          checkInBaggage: 15,
          airline: 'SG',
          airlineName: 'SpiceJet',
          arriveDate: '2023-10-09T09:20:00',
          departDate: '2023-10-09T08:20:00',
          destination: 'IXL',
          cabin: 'Economy',
          mileage: 0,
          handBaggage: 7,
          flightNumber: '8125',
          seatAvailable: 0,
          origin: 'DEL',
          classOfService: 'U',
          stops: 0,
          layoverAirportCode: null,
          layoverMinutes: 0,
          departTerminal: '3',
          arriveTerminal: null,
          seatMap: {
            seats: [
              {
                row: 1,
                column: 1,
                isAvailable: true,
                seatId: 0,
                seatNumber: '1A',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 1,
                column: 2,
                isAvailable: true,
                seatId: 1,
                seatNumber: '1B',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 1,
                column: 3,
                isAvailable: true,
                seatId: 2,
                seatNumber: '1C',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 1,
                column: 4,
                isAvailable: true,
                seatId: 3,
                seatNumber: '1D',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 1,
                column: 5,
                isAvailable: true,
                seatId: 4,
                seatNumber: '1E',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 1,
                column: 6,
                isAvailable: true,
                seatId: 5,
                seatNumber: '1F',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '1',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 1,
                isAvailable: true,
                seatId: 6,
                seatNumber: '2A',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 2,
                isAvailable: true,
                seatId: 7,
                seatNumber: '2B',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 3,
                isAvailable: true,
                seatId: 8,
                seatNumber: '2C',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 4,
                isAvailable: true,
                seatId: 9,
                seatNumber: '2D',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 5,
                isAvailable: true,
                seatId: 10,
                seatNumber: '2E',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 2,
                column: 6,
                isAvailable: true,
                seatId: 11,
                seatNumber: '2F',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 1,
                isAvailable: true,
                seatId: 12,
                seatNumber: '3A',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 2,
                isAvailable: true,
                seatId: 13,
                seatNumber: '3B',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 3,
                isAvailable: true,
                seatId: 14,
                seatNumber: '3C',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 4,
                isAvailable: true,
                seatId: 15,
                seatNumber: '3D',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 5,
                isAvailable: true,
                seatId: 16,
                seatNumber: '3E',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 3,
                column: 6,
                isAvailable: true,
                seatId: 17,
                seatNumber: '3F',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 1,
                isAvailable: true,
                seatId: 18,
                seatNumber: '4A',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 2,
                isAvailable: true,
                seatId: 19,
                seatNumber: '4B',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 3,
                isAvailable: true,
                seatId: 20,
                seatNumber: '4C',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 4,
                isAvailable: true,
                seatId: 21,
                seatNumber: '4D',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 5,
                isAvailable: true,
                seatId: 22,
                seatNumber: '4E',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 4,
                column: 6,
                isAvailable: true,
                seatId: 23,
                seatNumber: '4F',
                isExtraLegroom: true,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '4',
                },
                price: 999,
                name: null,
              },
              {
                row: 5,
                column: 1,
                isAvailable: true,
                seatId: 24,
                seatNumber: '5A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 5,
                column: 2,
                isAvailable: true,
                seatId: 25,
                seatNumber: '5B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 5,
                column: 3,
                isAvailable: true,
                seatId: 26,
                seatNumber: '5C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 5,
                column: 4,
                isAvailable: true,
                seatId: 27,
                seatNumber: '5D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 5,
                column: 5,
                isAvailable: true,
                seatId: 28,
                seatNumber: '5E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 5,
                column: 6,
                isAvailable: true,
                seatId: 29,
                seatNumber: '5F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 6,
                column: 1,
                isAvailable: true,
                seatId: 30,
                seatNumber: '6A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 6,
                column: 2,
                isAvailable: true,
                seatId: 31,
                seatNumber: '6B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 6,
                column: 3,
                isAvailable: true,
                seatId: 32,
                seatNumber: '6C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 6,
                column: 4,
                isAvailable: true,
                seatId: 33,
                seatNumber: '6D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 6,
                column: 5,
                isAvailable: true,
                seatId: 34,
                seatNumber: '6E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 6,
                column: 6,
                isAvailable: true,
                seatId: 35,
                seatNumber: '6F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 7,
                column: 1,
                isAvailable: true,
                seatId: 36,
                seatNumber: '7A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 7,
                column: 2,
                isAvailable: true,
                seatId: 37,
                seatNumber: '7B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 7,
                column: 3,
                isAvailable: true,
                seatId: 38,
                seatNumber: '7C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 7,
                column: 4,
                isAvailable: true,
                seatId: 39,
                seatNumber: '7D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 7,
                column: 5,
                isAvailable: true,
                seatId: 40,
                seatNumber: '7E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 7,
                column: 6,
                isAvailable: true,
                seatId: 41,
                seatNumber: '7F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 8,
                column: 1,
                isAvailable: true,
                seatId: 42,
                seatNumber: '8A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 8,
                column: 2,
                isAvailable: true,
                seatId: 43,
                seatNumber: '8B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 8,
                column: 3,
                isAvailable: true,
                seatId: 44,
                seatNumber: '8C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 8,
                column: 4,
                isAvailable: true,
                seatId: 45,
                seatNumber: '8D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 8,
                column: 5,
                isAvailable: true,
                seatId: 46,
                seatNumber: '8E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 8,
                column: 6,
                isAvailable: true,
                seatId: 47,
                seatNumber: '8F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 9,
                column: 1,
                isAvailable: true,
                seatId: 48,
                seatNumber: '9A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 9,
                column: 2,
                isAvailable: true,
                seatId: 49,
                seatNumber: '9B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 9,
                column: 3,
                isAvailable: true,
                seatId: 50,
                seatNumber: '9C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 9,
                column: 4,
                isAvailable: true,
                seatId: 51,
                seatNumber: '9D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 9,
                column: 5,
                isAvailable: true,
                seatId: 52,
                seatNumber: '9E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 9,
                column: 6,
                isAvailable: true,
                seatId: 53,
                seatNumber: '9F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 10,
                column: 1,
                isAvailable: true,
                seatId: 54,
                seatNumber: '10A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 10,
                column: 2,
                isAvailable: true,
                seatId: 55,
                seatNumber: '10B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 10,
                column: 3,
                isAvailable: true,
                seatId: 56,
                seatNumber: '10C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 10,
                column: 4,
                isAvailable: true,
                seatId: 57,
                seatNumber: '10D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 10,
                column: 5,
                isAvailable: true,
                seatId: 58,
                seatNumber: '10E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '6',
                },
                price: 99,
                name: null,
              },
              {
                row: 10,
                column: 6,
                isAvailable: true,
                seatId: 59,
                seatNumber: '10F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 11,
                column: 1,
                isAvailable: true,
                seatId: 60,
                seatNumber: '11A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '19',
                },
                price: 0,
                name: null,
              },
              {
                row: 11,
                column: 2,
                isAvailable: true,
                seatId: 61,
                seatNumber: '11B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '20',
                },
                price: 99,
                name: null,
              },
              {
                row: 11,
                column: 3,
                isAvailable: true,
                seatId: 62,
                seatNumber: '11C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '19',
                },
                price: 0,
                name: null,
              },
              {
                row: 11,
                column: 4,
                isAvailable: true,
                seatId: 63,
                seatNumber: '11D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '19',
                },
                price: 0,
                name: null,
              },
              {
                row: 11,
                column: 5,
                isAvailable: true,
                seatId: 64,
                seatNumber: '11E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '20',
                },
                price: 99,
                name: null,
              },
              {
                row: 11,
                column: 6,
                isAvailable: true,
                seatId: 65,
                seatNumber: '11F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '19',
                },
                price: 0,
                name: null,
              },
              {
                row: 12,
                column: 4,
                isAvailable: true,
                seatId: 66,
                seatNumber: '12D',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '21',
                },
                price: 0,
                name: null,
              },
              {
                row: 12,
                column: 5,
                isAvailable: true,
                seatId: 67,
                seatNumber: '12E',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '22',
                },
                price: 0,
                name: null,
              },
              {
                row: 13,
                column: 1,
                isAvailable: true,
                seatId: 68,
                seatNumber: '13A',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '9',
                },
                price: 999,
                name: null,
              },
              {
                row: 13,
                column: 2,
                isAvailable: true,
                seatId: 69,
                seatNumber: '13B',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '9',
                },
                price: 999,
                name: null,
              },
              {
                row: 13,
                column: 3,
                isAvailable: true,
                seatId: 70,
                seatNumber: '13C',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '9',
                },
                price: 999,
                name: null,
              },
              {
                row: 13,
                column: 4,
                isAvailable: true,
                seatId: 71,
                seatNumber: '13D',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '23',
                },
                price: 0,
                name: null,
              },
              {
                row: 13,
                column: 5,
                isAvailable: true,
                seatId: 72,
                seatNumber: '13E',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '24',
                },
                price: 0,
                name: null,
              },
              {
                row: 13,
                column: 6,
                isAvailable: true,
                seatId: 73,
                seatNumber: '13F',
                isExtraLegroom: true,
                isExitRow: true,
                isSeatPresent: true,
                isReclining: false,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '9',
                },
                price: 999,
                name: null,
              },
              {
                row: 14,
                column: 1,
                isAvailable: true,
                seatId: 74,
                seatNumber: '14A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 14,
                column: 2,
                isAvailable: true,
                seatId: 75,
                seatNumber: '14B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 14,
                column: 3,
                isAvailable: true,
                seatId: 76,
                seatNumber: '14C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 14,
                column: 4,
                isAvailable: true,
                seatId: 77,
                seatNumber: '14D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 14,
                column: 5,
                isAvailable: true,
                seatId: 78,
                seatNumber: '14E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 14,
                column: 6,
                isAvailable: true,
                seatId: 79,
                seatNumber: '14F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 15,
                column: 1,
                isAvailable: true,
                seatId: 80,
                seatNumber: '15A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 15,
                column: 2,
                isAvailable: true,
                seatId: 81,
                seatNumber: '15B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 15,
                column: 3,
                isAvailable: true,
                seatId: 82,
                seatNumber: '15C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 15,
                column: 4,
                isAvailable: true,
                seatId: 83,
                seatNumber: '15D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 15,
                column: 5,
                isAvailable: true,
                seatId: 84,
                seatNumber: '15E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 15,
                column: 6,
                isAvailable: true,
                seatId: 85,
                seatNumber: '15F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 16,
                column: 1,
                isAvailable: true,
                seatId: 86,
                seatNumber: '16A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 16,
                column: 2,
                isAvailable: true,
                seatId: 87,
                seatNumber: '16B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 16,
                column: 3,
                isAvailable: true,
                seatId: 88,
                seatNumber: '16C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 16,
                column: 4,
                isAvailable: true,
                seatId: 89,
                seatNumber: '16D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 16,
                column: 5,
                isAvailable: true,
                seatId: 90,
                seatNumber: '16E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 16,
                column: 6,
                isAvailable: true,
                seatId: 91,
                seatNumber: '16F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 17,
                column: 1,
                isAvailable: true,
                seatId: 92,
                seatNumber: '17A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 17,
                column: 2,
                isAvailable: true,
                seatId: 93,
                seatNumber: '17B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 17,
                column: 3,
                isAvailable: true,
                seatId: 94,
                seatNumber: '17C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 17,
                column: 4,
                isAvailable: true,
                seatId: 95,
                seatNumber: '17D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 17,
                column: 5,
                isAvailable: true,
                seatId: 96,
                seatNumber: '17E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 17,
                column: 6,
                isAvailable: true,
                seatId: 97,
                seatNumber: '17F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 18,
                column: 1,
                isAvailable: true,
                seatId: 98,
                seatNumber: '18A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 18,
                column: 2,
                isAvailable: true,
                seatId: 99,
                seatNumber: '18B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 18,
                column: 3,
                isAvailable: true,
                seatId: 100,
                seatNumber: '18C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 18,
                column: 4,
                isAvailable: true,
                seatId: 101,
                seatNumber: '18D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 18,
                column: 5,
                isAvailable: true,
                seatId: 102,
                seatNumber: '18E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 18,
                column: 6,
                isAvailable: true,
                seatId: 103,
                seatNumber: '18F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 19,
                column: 1,
                isAvailable: true,
                seatId: 104,
                seatNumber: '19A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 19,
                column: 2,
                isAvailable: true,
                seatId: 105,
                seatNumber: '19B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 19,
                column: 3,
                isAvailable: true,
                seatId: 106,
                seatNumber: '19C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 19,
                column: 4,
                isAvailable: true,
                seatId: 107,
                seatNumber: '19D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 19,
                column: 5,
                isAvailable: true,
                seatId: 108,
                seatNumber: '19E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 19,
                column: 6,
                isAvailable: true,
                seatId: 109,
                seatNumber: '19F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 20,
                column: 1,
                isAvailable: true,
                seatId: 110,
                seatNumber: '20A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 20,
                column: 2,
                isAvailable: true,
                seatId: 111,
                seatNumber: '20B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 20,
                column: 3,
                isAvailable: true,
                seatId: 112,
                seatNumber: '20C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 20,
                column: 4,
                isAvailable: true,
                seatId: 113,
                seatNumber: '20D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 20,
                column: 5,
                isAvailable: true,
                seatId: 114,
                seatNumber: '20E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '15',
                },
                price: 49,
                name: null,
              },
              {
                row: 20,
                column: 6,
                isAvailable: true,
                seatId: 115,
                seatNumber: '20F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 21,
                column: 1,
                isAvailable: true,
                seatId: 116,
                seatNumber: '21A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 21,
                column: 2,
                isAvailable: true,
                seatId: 117,
                seatNumber: '21B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 21,
                column: 3,
                isAvailable: true,
                seatId: 118,
                seatNumber: '21C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 21,
                column: 4,
                isAvailable: true,
                seatId: 119,
                seatNumber: '21D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 21,
                column: 5,
                isAvailable: true,
                seatId: 120,
                seatNumber: '21E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 21,
                column: 6,
                isAvailable: true,
                seatId: 121,
                seatNumber: '21F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 22,
                column: 1,
                isAvailable: true,
                seatId: 122,
                seatNumber: '22A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 22,
                column: 2,
                isAvailable: true,
                seatId: 123,
                seatNumber: '22B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 22,
                column: 3,
                isAvailable: true,
                seatId: 124,
                seatNumber: '22C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 22,
                column: 4,
                isAvailable: true,
                seatId: 125,
                seatNumber: '22D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 22,
                column: 5,
                isAvailable: true,
                seatId: 126,
                seatNumber: '22E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 22,
                column: 6,
                isAvailable: true,
                seatId: 127,
                seatNumber: '22F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 23,
                column: 1,
                isAvailable: true,
                seatId: 128,
                seatNumber: '23A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 23,
                column: 2,
                isAvailable: true,
                seatId: 129,
                seatNumber: '23B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 23,
                column: 3,
                isAvailable: true,
                seatId: 130,
                seatNumber: '23C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 23,
                column: 4,
                isAvailable: true,
                seatId: 131,
                seatNumber: '23D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 23,
                column: 5,
                isAvailable: true,
                seatId: 132,
                seatNumber: '23E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 23,
                column: 6,
                isAvailable: true,
                seatId: 133,
                seatNumber: '23F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 24,
                column: 1,
                isAvailable: true,
                seatId: 134,
                seatNumber: '24A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 24,
                column: 2,
                isAvailable: true,
                seatId: 135,
                seatNumber: '24B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 24,
                column: 3,
                isAvailable: true,
                seatId: 136,
                seatNumber: '24C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 24,
                column: 4,
                isAvailable: true,
                seatId: 137,
                seatNumber: '24D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 24,
                column: 5,
                isAvailable: true,
                seatId: 138,
                seatNumber: '24E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 24,
                column: 6,
                isAvailable: true,
                seatId: 139,
                seatNumber: '24F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 25,
                column: 1,
                isAvailable: true,
                seatId: 140,
                seatNumber: '25A',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 25,
                column: 2,
                isAvailable: true,
                seatId: 141,
                seatNumber: '25B',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 25,
                column: 3,
                isAvailable: true,
                seatId: 142,
                seatNumber: '25C',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 25,
                column: 4,
                isAvailable: true,
                seatId: 143,
                seatNumber: '25D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 25,
                column: 5,
                isAvailable: true,
                seatId: 144,
                seatNumber: '25E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 25,
                column: 6,
                isAvailable: true,
                seatId: 145,
                seatNumber: '25F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 26,
                column: 4,
                isAvailable: true,
                seatId: 146,
                seatNumber: '26D',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
              {
                row: 26,
                column: 5,
                isAvailable: true,
                seatId: 147,
                seatNumber: '26E',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '8',
                },
                price: 0,
                name: null,
              },
              {
                row: 26,
                column: 6,
                isAvailable: true,
                seatId: 148,
                seatNumber: '26F',
                isExtraLegroom: false,
                isExitRow: false,
                isSeatPresent: true,
                isReclining: true,
                isWing: false,
                seatLocation: 2,
                seatSupplierState: {
                  key: '7',
                },
                price: 250,
                name: null,
              },
            ],
          },
          mealOptions: [
            {
              imgUrl: 'https://static.udchalo.com/client_assets/img/meals/spicejet/VGSW.png',
              code: 'VGSW',
              price: 385,
              text: 'Veg Sandwich',
            },
            {
              imgUrl: 'https://static.udchalo.com/client_assets/img/meals/spicejet/NVSW.png',
              code: 'NVSW',
              price: 434,
              text: 'Non Veg Sandwich',
            },
          ],
          handBaggageText: null,
          fareBasisCode: 'USAV',
          originCountryCode: 'IN',
          destinationCountryCode: 'IN',
        },
      ],
      checkInBaggage: 15,
      handBaggage: 7,
      provider: 'SpicejetAPIV4',
      mode: 'TEST',
      isExclusive: false,
      isLtcEligible: false,
      isLtcEntitled: false,
      cancelPenalties: [
        {
          amount: 3500,
          hours: 24,
          penaltyType: 0,
          additionalGstPercent: 0,
        },
        {
          amount: 3000,
          hours: 96,
          penaltyType: 0,
          additionalGstPercent: 0,
        },
      ],
      reschedulePenalties: [
        {
          amount: 3000,
          hours: 24,
          penaltyType: 0,
          additionalGstPercent: 0,
        },
        {
          amount: 2500,
          hours: 96,
          penaltyType: 0,
          additionalGstPercent: 0,
        },
      ],
      excessBaggageOptions: [
        {
          code: 'EB05',
          price: 2250,
          text: '5 Kg Extra',
        },
        {
          code: 'EB10',
          price: 4500,
          text: '10 Kg Extra',
        },
      ],
      handBaggageText: null,
      supplierState: {
        fareKey: '0~U~ ~SG~USAV~5511~~0~5~~X',
        ruleNumber: '5511',
        productClass: 'RS',
        sellKey: 'SG~8125~ ~~DEL~10/09/2023 08:20~IXL~10/09/2023 09:20~~',
        signature:
          'vrjj6r2Y50I=|kp9DjgYMuDztSXT4XrYAy/wCVR0MIqemVtb1oe8P8BOiZbr/iz43J79bKb5dwkCbdw4yU0RPXSJXjZ4CA4V3M2AWxTSvPVbHJSF2QznF9rKaoe8rcvpLhQkcPCTjOrNdHhoM7+fUHtY=',
        signatureTimeStamp: '2023-10-08T05:02:35.176Z',
        pricingTimeStamp: '2023-10-08T05:11:44.167Z',
      },
    },
    flightId: '98b7c141-5823-4499-8cac-ba63877b405d',
    priceDiff: 0,
  },
];

export const search = {
  origin: 'DEL',
  infants: 0,
  departDate: '2023-10-09T00:00:00',
  endUserIp: '1.23.230.223',
  originCountryCode: 'IN',
  createdAt: '2023-10-08T05:01:32.281Z',
  source: 'app',
  children: 0,
  userVerificationStatus: 'UFFconsented',
  tripType: 'oneway',
  isLTCClaim: false,
  sessionId: '0ecd52d5-9e66-431d-9a35-e71d380dcccc',
  isCovidBooking: false,
  isDefence: false,
  userId: 'a09072ac-aad2-4d45-acb2-3d7658b55a66',
  expirationTime: 1698469292,
  destinationCountryCode: 'IN',
  isLTCTab: false,
  destination: 'IXL',
  isEnabled: 1,
  cabin: 'Economy',
  adults: 1,
  isLoggedIn: true,
};
